services:
  hr_interview:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_interview
    expose:
      - 65535:65535
    networks:
      - careerspeak

networks:
  careerspeak:
    external: true
